### ISSUE TITLE
Replace travis ci?

### ISSUE THREAD

**Issue by PelleUllberg** [klarna/HiveRunner#100]
Hi, Just noticed this. https://medium.com/@dirk.avery/r-i-p-travis-ci-347753c73775 
Maybe old news but maybe some other CI engines should be considered?

regards
/Pelle

**Comment by massdosage** [comment]
I don't think we should overreact, let's wait and see and what happens with Travis. We've looked at numerous alternatives over the years and they all have their pros and (more often than not) cons. For now I'm not convinced there is anything as feature-rich as Travis so I'd suggest we stick with it for now. If for some reason open source Travis is closed down I'm sure there will be a huge number of people in the same boat as us and there will be plenty of migrations going on. From past experience (e.g. Google Code closing down), if you wait a bit the migration becomes even easier as the destination tools start building migration tools you can leverage (with Google Code it ended up so you basically just clicked a button on the project was migrated over to GitHub). 

Unless someone really objects or wants to spend time investigating an alternative I'd suggest closing this for now.

**Comment by PelleUllberg** [comment]
Fair points, just wanted to make people aware. You can close it. I guess
there can still be a discussion in the closed issue?

regards
/Pelle

**Comment by massdosage** [comment]
For sure, we can also re-open if things really go badly at Travis and we do need to do this.
