### ISSUE TITLE
DROP TABLE IF EXISTS logged as error if the table doesn't exist

### ISSUE THREAD

**Issue by lhsvobodaj** [klarna/HiveRunner#105]
**Describe the bug**
When running a `DROP TABLE IF EXISTS` statement and the referenced table doesn't exist, a log entry with `ERROR` severity is displayed.

**To Reproduce**
```java
package ae.pax.subscriber;

import com.klarna.hiverunner.HiveShell;
import com.klarna.hiverunner.StandaloneHiveRunner;
import com.klarna.hiverunner.annotations.HiveSQL;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(StandaloneHiveRunner.class)
public class DropTableIfExistsTest {

    @HiveSQL(files = {})
    private HiveShell shell;

    @Test
    public void shouldDropTableIfExists() {

        shell.executeQuery("create database my_db");
        shell.executeQuery("use my_db");
        shell.executeQuery("drop table if exists my_db.my_table");
        shell.executeStatement("drop table if exists my_db.my_table");

    }
}
```

**Expected behavior**
An `INFO` log reporting the table does not exist.

**Logs**
```
OK
OK
OK
11:38:08.188 [52bd8d48-a712-4e9f-9df0-79cce13a9eb2 Thread-1] ERROR hive.ql.metadata.Hive - Table muy_table not found: my_db.my_table table not found
OK
11:38:08.313 [52bd8d48-a712-4e9f-9df0-79cce13a9eb2 Thread-1] ERROR hive.ql.metadata.Hive - Table muy_table not found: my_db.my_table table not found
OK
OK
```

**Versions (please complete the following information):**
 - HiveRunner Version: 4.1.0
 - Hive Versions: 2.1.1

**Comment by massdosage** [comment]
This doesn't fail the test but is just a log message right? That message is coming from Hive itself (https://github.com/apache/hive/blob/rel/release-2.3.4/ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java#L1277) so there's not really anything we can do about it from HiveRunner as we're just executing Hive's code at that point and can't intervene. If it's really bothering you then you could probably update the logging configuration for your tests to exclude ERROR messages from the above class.

**Comment by lhsvobodaj** [comment]
Correct! The test doesn't fail; it is just the ERROR message in the log that looks very strange as there is no actual error. I was checking the Hive code, and to change the severity it won't be so easy as the [getTable](https://github.com/apache/hive/blob/rel/release-2.3.4/ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java#L1264) method is used in several places, and in some of them maybe makes sense to keep the log as an error (although I still don't fully agree with the severity).

Let's close this issue as it is not related to HiveRunner and I will just tell our team to get used to that ERROR message in the logs. 😉

**Comment by massdosage** [comment]
Sounds good!
