### ISSUE TITLE
JUnit 5 support: HiveRunner as an Extension

### ISSUE THREAD

**Issue by j-seps** [klarna/HiveRunner#106]
StandaloneHiveRunner is a JUnit 4 Runner. I don' think there exists a JUnit 5 Extension.

If there is a JUnit 5 HiveRunner Extension, we could combine it with JUnit 5 extensions like Mockito, Cucumber, ...

**Comment by massdosage** [comment]
At the moment there isn't support for JUnit 5. This is definitely something we'd like to do, I can't say when we'll get around to implementing this so in the interim pull requests adding this feature would be welcome. Ideally we'd want to be able to do it in a manner that's backwards compatible for JUnit 4 but I'm not sure whether that's possible.

**Comment by PelleUllberg** [comment]
I haven’t looked at junit5 but I’d be surprised if it could not be made
backwards compatible. I guess the current runner can be kept as is and then
the junit5 apis could be implemented in parallel?

/Pelle

**Comment by j-seps** [comment]
JUnit 5 no longer supports the JUnit 4 Rules (used in the StandaloneHiveRunner class), but introduced JUnit 5 Extensions that can be used to replace the behaviour of these Rules.

I think the functionality in the StandaloneHiveRunner which concerns HiveShell and HiveConfig can be moved to a seperate class. 
- So the StandaloneHiveRunner (which extends the BlockJUnit4ClassRunner) can call the correct methods of this new class
- And the new JUnit 5 Extension (which implements the JUnit 5 Extension interfaces) can also call these methods of this new class (and re-use the existing functionality)

**Comment by PelleUllberg** [comment]
Big question is if the source may be compiled with both junit4 and junit5
dependencies? Otherwise it has to be branched or multimoduled.

/Pelle

**Comment by JayGreeeen** [comment]
Support for this is currently in progress in this [fork](https://github.com/cmathiesen/HiveRunner/pull/1)

**Comment by massdosage** [comment]
Released in HiveRunner 5.0.0.
