### ISSUE TITLE
Allow hiveshell insert to Parquet tables

### ISSUE THREAD

**Issue by alexdgarland** [klarna/HiveRunner#108]
We have found that when inserting data to tables using the [HiveShell insertInto method](https://github.com/klarna/HiveRunner/blob/master/src/main/java/com/klarna/hiverunner/HiveShell.java#L321) fails where the table uses Parquet storage.

This is similar to https://github.com/klarna/HiveRunner/issues/82 and generates the same error (`java.lang.RuntimeException: Should never be used`) but a **distinct** issue in that the table creation now seems to work but the error happens when data is inserted.

We are currently working around by staging data into ORC-stored tables but would really like this to work as Parquet is a very popular format we want to make more use of.

We have traced the likely cause to the fact that HiveRunner [uses HCatalog for the insert](https://github.com/klarna/HiveRunner/blob/master/src/main/java/com/klarna/hiverunner/data/TableDataInserter.java#L59) and that [by the look of things](https://issues.apache.org/jira/browse/HIVE-8838) HCatalog added proper support for Parquet considerably later than Hive?

There are therefore two paths we have discussed (internally to Hotels.com with @patduin) that could be tried:
- testing and validating [this pull request](https://github.com/klarna/HiveRunner/pull/93) to get support for Hive 3.0.0 implemented
- changing the way that HiveRunner handles the insert so that HCatalog is not a factor and any version of Hive can be used with Parquet inserts. This is useful as we want to be able to thoroughly test against the exact version of Hive we have in production (currently 2.1.x and 2.3.x depending on age of data pipeline)

**Comment by massdosage** [comment]
This may now be resolved as https://issues.apache.org/jira/browse/HIVE-22249 was merged and released in HIve 2.3.7 which in turn HiveRunner now uses in the latest released version. @alexdgarland is this something you can reproduce and try out with HiveRunner 5.2.0? A PR with a test to reproduce (or even just a code snippet) would be appreciated too.

**Comment by alexdgarland** [comment]
Hiya @massdosage - thanks for the update. This sits with my old dev team but I'll see if either I or they can take a look at this in the next few days to validate.
