### ISSUE TITLE
Hive 2.3.6

### ISSUE THREAD

**Issue by labbedaine** [klarna/HiveRunner#117]
Hello, I need some guidance on how to use a different version of Hive.

HiveRunner-5.1.0 is using version 2.3.4 of Apache Hive but our production code is on 2.3.6  What would be the best way to make sure my unit tests are running against the Hive version I am using in AWS/emr (2.3.6)

Thank you!

**Comment by massdosage** [comment]
If you would like to ask any questions about or discuss HiveRunner please join our mailing list and ask at

https://groups.google.com/forum/#!forum/hive-runner-user
