### ISSUE TITLE
Tests Fail when setting hive.exec.dynamic.partition.mode = nonstrict;

### ISSUE THREAD

**Issue by philltomlinson** [klarna/HiveRunner#124]
**Describe the bug**
I have some Hive Scripts that use the dynamic partition mode = nonstrict, as some of my scripts load data from many partitions. 

**To Reproduce**
Within a hive script set:
SET hive.exec.dynamic.partition.mode = nonstrict;
And the test will fail.

**Expected behavior**
Test case to pass.

**Logs**
Nothing shows up in the logs pointing to an error, the test case will not pass.

**Versions (please complete the following information):**
 - HiveRunner Version: 5.2.1
 - Hive Versions: 2.3.7

**Additional context**

**Comment by massdosage** [comment]
Looks like this could be a duplicate of #94

**Comment by philltomlinson** [comment]
Thanks @massdosage the screenshot on #94 matches what behaviour I see.
