### ISSUE TITLE
HIveRunner keeps failing

### ISSUE THREAD

**Issue by rohitbordia** [klarna/HiveRunner#34]
I keep getting the below error and could not find which jar im skipping. I'm not able to find the below class in ay of jar.

2016-04-05 08:59:59     DEBUG     HiveServerContainer : 173    -    org/apache/hadoop/fs/FSDataInputStream$FadviseType  
java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream$FadviseType
	at org.apache.hadoop.mapred.LineRecordReader.close(LineRecordReader.java:284)

**Comment by rohitbordia** [comment]
Looks like , I did some config changes and know im stuck at :All resource target files should be created in a subdirectory to the test case basedir 

Somehow need to find where the standaloneHiveRunner is creating the dir.

**Comment by PelleUllberg** [comment]
Hi, Sorry for a very late reply

You can retrieve the basedir of your hiverunner test either by [HiveShell#getBaseDir()](https://github.com/klarna/HiveRunner/blob/master/src/main/java/com/klarna/hiverunner/HiveShell.java#L210) or through hive configuration property ${hiveconf:hadoop.tmp.dir}.

Hope that helps!

/Pelle
