### ISSUE TITLE
Constructors are private of HIveServerContainer,StandaloneHiveServrContainer,HiveServerContext,StandaloneHiveServerContext

### ISSUE THREAD

**Issue by prachi94** [klarna/HiveRunner#35]
If anyone has to start the shell manually, can't make instances of StandaloneHiveServerContainer and StandaloneHiveServerCOntainer because constructor are protected so can't be accessed

**Comment by PelleUllberg** [comment]
True, We could probably make those constructors public. Please make a new attempt at a Pull Request.

regards
/Pelle

**Comment by massdosage** [comment]
Closing since no feedback received for over a year.
