### ISSUE TITLE
keep getting ERROR org.apache.hadoop.hive.ql.exec.mr.ExecDriver - local 

### ISSUE THREAD

**Issue by chenxi969** [klarna/HiveRunner#40]
Hi there, 

I'm trying to run HelloHiveRunner and keep getting ERROR org.apache.hadoop.hive.ql.exec.mr.ExecDriver    - local. The test cases seem still work though.

Do you have any idea why I keep getting this error message?

Thanks in advance!

**Comment by PelleUllberg** [comment]
Could you provide some more information? Could you provide something that reproduces the error? 

A long shot: Make sure you don't have any hive-site.xml or other *-site.xml files on the classpath when executing HiveRunner. It might be that it sucks up config from those files and that would tamper with the way HiveRunner runs in local mode.

regards
/Pelle
