### ISSUE TITLE
Hive can do unit testing with hbase？

### ISSUE THREAD

**Issue by swen7** [klarna/HiveRunner#41]
hi，Hiverunnner is able to unit test with hbase?  if it can ,how to configure unit test hbase.
here is the hive table with hbase  ：
CREATE TABLE test_hive_hbase (
  key string COMMENT '',
  teststr int COMMENT '')
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES (
  'hbase.columns.mapping'=':key,teststr:1')
TBLPROPERTIES ('hbase.table.name'='test_hbase')

**Comment by PelleUllberg** [comment]
Hi, Never tried that. It might be possible to get HiveRunner to connect to a running HBase instance but I never tried it. 

Consider HiveRunner more of a unit test fwk than an integration test fwk. You should focus on testing your query logic with hiverunner. With that said, you could easily mock your hbase backed table with a filesystem based table instead to try your queries on that table instead.

regards
/Pelle
