### ISSUE TITLE
Hive Runner on Windows using Cygwin

### ISSUE THREAD

**Issue by snehaabr** [klarna/HiveRunner#45]
Getting below exception while running hiverunner on Windows:
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:172)
    at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:64)
    at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:91)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
    at java.lang.Thread.run(Thread.java:745)

However the test runs successfully on Mac. I have installed Cygwin. Please guide on how to utlize Cygwin to work with Hiverunner.

**Comment by adamdec** [comment]
Having the same on version 3.0.0

**Comment by PelleUllberg** [comment]
Sorry, but there's no official guide on how to run HiveRunner on cygwin. I'll ask around to see if someone with experience of that can comment here.

best regards
/Pelle

**Comment by workasr** [comment]
I think this is a generic Windows problem.  I get the same problem running maven from Windows command line.  It looks like it has something to do with Windows permissions (which  I do not understand at all!).
This is the command that is failing:
`Assert.assertTrue(temporaryFolder.getRoot().setWritable(true, false));`

The folder is a random junit dir created in the windows TEMP dir.
This is a great tool and I want to use it but it is onerous to have to move my dev env to a Linux box.
BTW - if you comment out those Asserts, it will fail in hive commands later on, e.g.

> java.lang.IllegalStateException: Failed to create HiveServer :Error applying authorization policy on hive configuration: The root scratch dir: D:/tmp/junit3112167780932549218/scratchdir on HDFS should be writable. Current permissions are: rwx------

**Comment by jvmlet** [comment]
Hi
Any updates about this  issue ?

**Comment by PelleUllberg** [comment]
Hi,

Sorry to disappoint you but we don't develop on Windows and have no success
stories from others using winfows togetreh with HiveRunner either. We have
internal users that need to use windows machines for other reasons and we
have a ticket on our internal backlog to find a way to support our windows
users but it's unfortunately far down the backlog at the moment.

One way could be to run the tests in a docker container or such. However,
IDE integration with docker is not yet great. Any ideas and solutions are
more than welcome on this subject.

best regards
/Per Ullberg

**Comment by jvmlet** [comment]
@PelleUllberg , I've noticed that in my Windows environment the tmp folder misses `Special permissions` for admin user and I can't change it because of the company policies  to check if it solves the problem. 

![image](https://cloud.githubusercontent.com/assets/6664858/19846351/2cde6f02-9f47-11e6-96bd-8fe381f16898.png)

Worth to try to see if `file.setWritable` implementation some how depends on it.

**Comment by jvmlet** [comment]
On the other hand, the `Files.isWritable(temporaryFolder.getRoot())` returns `true` if i set breakpoint on  `Assert.assertTrue(temporaryFolder.getRoot().setWritable(true, false));`
line.
Also ,I can write to  `new TemporaryFolder()` from  the same unit test, so may be the `Assert` could be conditional on the result of Files.isWritable(temporaryFolder.getRoot())

**Comment by jvmlet** [comment]
I was able to overcome  this issue manually by commenting out Asserts on `setWritable` result, and then, while in debug, I took the generated `/scratchdir` folder  and run 
`winutils.exe chmod 777 ${scratchdir} `
then resumed the test.
May be this could be done automatically.\

Another issue I hive with the `@RunWith(StandaloneHiveRunner.class)`, my test class looks like this :
````java
@RunWith(StandaloneHiveRunner.class)
@SpringApplicationConfiguration(classes = TestApplication.class)
public class BsodEtlTest extends AbstractJUnit4SpringContextTests {
    @Autowired
    private PipelinesSettings pipelinesSettings;
 // ommited
}
````
The `pipelinesSettings`  does't get injected  with the `StandaloneHiveRunner`...
@PelleUllberg Do you want me to open another issue on this ?
Thanks

**Comment by oleksandr-yatsuk** [comment]
Guys, I've created a [pull request](https://github.com/klarna/HiveRunner/pull/63) regarding the permissions issue described above.
Please review it.

**Comment by johnsonlarryl** [comment]
@PelleUllberg, are you all planning to push v 3.2.1 to Maven Central soon?  Is there anyway I can help?

**Comment by massdosage** [comment]
HiveRunner 3.2.1 was released today and contains the fix from the above PR.
