### ISSUE TITLE
Support headers in TSVFileParser

### ISSUE THREAD

**Issue by while** [klarna/HiveRunner#59]
It would be really neat if I could use `insertInto` with `TsvFileParser` where only a few columns were specified and hence selected as now done with `withColumns`. 

My use case is where I have a lot of tests that all have different csv input files where not all columns are needed. When I do schema changes I would preferrably only like to change the tests that are affected and not have a lot of empty values. To know which columns are used in which CSV it is easiest to have a header which is currently not supported.

**Comment by while** [comment]
Added a pull request for this feature.

**Comment by massdosage** [comment]
I assume this is the issue referred to in the CHANGELOG for the 3.2.0 release:
```
[3.2.0] - 2017-02-09
Added

    Added functionality for headers in TSV parser. This way you can dynamically add TSV files declaring a subset of columns using insertInto.
```
