### ISSUE TITLE
JSON to array of struct

### ISSUE THREAD

**Issue by oleksandr-yatsuk** [klarna/HiveRunner#64]
Hi guys,

I have a table with a column of type array<struct<property1:string, property2:string>> and I have a *.csv file with values I want to insert into this table.
I am trying to insert into array<struct> column JSON ([{"property1": "1", "property2": "2"}]")  and of course it is failing.
So there is a question: does exist some workaround to insert values into column of array type with HiveShell?

**Comment by alexkcode** [comment]
You can do it in Java with just a List type (according to this post https://stackoverflow.com/questions/26026027/how-to-return-struct-from-hive-udf they are equivalent)

```
shell.execute("CREATE TABLE test_db.test (" +
        "  testStruct struct<test : STRING>)");

ArrayList<String> values = new ArrayList<String>();
    values.add("potato");
    shell.insertInto("test_db", "test")
    .withAllColumns()
    .addRow(values)
    .commit();
```

**Comment by massdosage** [comment]
Hopefully one or both of the above suggestions have resolved the issue which looks like it's more a general Hive question than anything to do with HiveRunner.
