### ISSUE TITLE
NoSuchFieldError: doubleTypeInfo

### ISSUE THREAD

**Issue by ksimbv** [klarna/HiveRunner#68]
Hello,

I am currently getting a `NoSuchFieldError` for `doubleTypeInfo` when creating an external table with fields of type `DOUBLE`:

    CREATE EXTERNAL TABLE IF NOT EXISTS <db_name.table_name> (
        name STRING,
        avgrating DOUBLE
    ): Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. doubleTypeInfo

    FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. doubleTypeInfo
    ERROR [2017-04-06 15:17:45,762] hive.ql.exec.DDLTask: java.lang.NoSuchFieldError: doubleTypeInfo

Any advice is appreciated. Thanks.

**Comment by PelleUllberg** [comment]
Are you missing some dependency on the classpath? Sorry, I'm on vacation
and only on my iPhone.

But check your classpath for missing dependencies.

/pelle

**Comment by ksimbv** [comment]
Thanks for replying during your vacation. 

I explicitly added hive-serde in my pom to make sure `TypeInfoFactory::doubleTypeInfo` is present but I am getting the same outcome.

**Comment by massdosage** [comment]
Could you please try HiveRunner 3.2.1 (which was released today) and let us know if this is still an issue? If so could you please output a list of all the Hive dependencies that Maven is using?

**Comment by massdosage** [comment]
Closing since no feedback received on above comment.
