### ISSUE TITLE
Aggregate functions with Views

### ISSUE THREAD

**Issue by thecharlieblake** [klarna/HiveRunner#70]
Hi,

I've been having a rather unusual problem involving using an aggregate function, storing the result in a view, and then accessing the data in that view.

I have the following two queries, which I run in sequence:

```
CREATE VIEW db.latestnodemvtchanges AS
SELECT testid, hostname, max(`timestamp`) AS mts
FROM db.mvtdescriptionchangeinfo
WHERE `timestamp` IS NOT NULL
GROUP BY testid, hostname;
```

```
CREATE VIEW db.latesttestchangepairs AS
SELECT a.testid, a.type
FROM db.mvtdescriptionchangeinfo a
INNER JOIN db.latestnodemvtchanges b ON a.testid = b.testid AND a.`timestamp` = b.mts
GROUP BY a.testid, a.type;
```

And check the result using:

```
SELECT * FROM db.latesttestchangepairs
```

and to set this all up, beforehand I execute:

```
CREATE DATABASE db;

CREATE EXTERNAL TABLE `db.mvtdescriptionchangeinfo`(
  `timestamp` bigint COMMENT '',
  `testid` string COMMENT '',
  `type` string COMMENT '',
  `contents` string COMMENT '',
  `hostname` string COMMENT '')
PARTITIONED BY (
  `request_log_date` string,
  `request_log_hour` string)
```

My problem is as follows: when I unit test the first query it behaves exactly as expected, finding the maximum timestamp and filtering the others out accordingly. The second query also does what it's supposed to when tested by itself.

However, when I combine the two, something strange happens - the line ``a.`timestamp` = b.mts`` stops working as it should. Even when I have one row in both tables that the query accesses, with identical timestamps, the condition ``a.`timestamp` = b.mts`` doesn't return true and as a consequence nothing is returned. When I remove this condition the join works as expected.

The test input to db.mvtdescriptionchangeinfo I use is:
`123	testname	REMOVED	"contents of test..."	hostname	6/21/17	20`

The output I should get is:
`testname	REMOVED`

but instead nothing is returned.

I've traced this back to the ``max(`timestamp`)`` aggregate function in the first query. It seems to be causing the issue, as when I simply replace it with the timestamp value '123' (which is what ``max(`timestamp`)`` should return), everything works.

Again, when I replace ``a.`timestamp` = b.mts`` in the second query with ``a.`timestamp` = 123`` then it works as I would expect, and even when I replace that same line with `123 = b.mts` it all works as expected. It's just comparing them to each other which causes this to fail.

I really can't figure out why this would happen. My hunch is that it might be something to do with the way that views calculate aggregate functions. Why this would happen because of something in HiveRunner I'm not sure, and having run this on an actual hive test server everything worked. Still, the problem persists, so I thought I'd let you know and hopefully you can reproduce and diagnose it. 

I hope that's enough information about the problem. Let me know how else I can help with this. Thanks!

**Comment by massdosage** [comment]
Appears to have been an issue with Hive 1.x which has been resolved in 2.x. https://github.com/klarna/HiveRunner/pull/144 contains a unit test which demonstrates this working.
