### ISSUE TITLE
Case-insensitive bug fix

### ISSUE THREAD

**Issue by JayGreeeen** [klarna/HiveRunner#73]
There was a bug which meant that if a file contained an uppercase letter in the column name, it wouldn't register that it was the same name as the column in the table to add the data to, as they are read as lower-case names.
I fixed this by converting the names from the file to lower case when they are read in, in the following PR; [https://github.com/klarna/HiveRunner/pull/72](url)

**Comment by sid88in** [comment]
@JayGreeeen https://github.com/klarna/HiveRunner/pull/72 doesn't exist?  404

**Comment by massdosage** [comment]
Code has been merged to master, targetted at 3.2.1 release. Thanks for contributing!
