### ISSUE TITLE
3.2.1 release to maven repository

### ISSUE THREAD

**Issue by hardfire** [klarna/HiveRunner#81]
Since 3.2.1 fixes the windows issue and it's been in the repository for some time, I'm curious when would this be published to the maven repository?
Great work and thanks for this btw!

**Comment by massdosage** [comment]
I'll be looking at cutting a release sometime in the next couple of weeks, I'm a new contributor to the project so bear with me as it might take a few attempts!

**Comment by massdosage** [comment]
Code in master is ready to go, the build is failing on releasing artifacts with some GPG key issues which I'll be looking into next.

**Comment by massdosage** [comment]
3.2.1 was released to Maven Central today: http://repo1.maven.org/maven2/com/klarna/hiverunner/3.2.1/
