### ISSUE TITLE
How to run test on Hadoop Cluster

### ISSUE THREAD

**Issue by Gaurang033** [klarna/HiveRunner#85]
hi Guys, 

I am trying to use this tool to write the unit test for my hive SQL and it's working as expected when I run on local machine. However, I would like to understand how to run this test on my existing hadoop cluster. 
is there any configuration change I need to make so that it runs on exiting cluster and use exiting HDFS.

**Comment by PelleUllberg** [comment]
Hi, hiverunner only supports running tests in local jvm. You’d have to run
a different tool for running this on your cluster or add this feature to
Hiverunner.

Best regards
/Pelle
