### ISSUE TITLE
SemanticException End of a WindowFrame cannot be UNBOUNDED PRECEDING

### ISSUE THREAD

**Issue by charavana** [klarna/HiveRunner#87]
Hi Team,
Can you update the hive version used from 0.10.0 to latest 

its not supporting the below:
org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException End of a WindowFrame cannot be UNBOUNDED PRECEDING and many other data analytics

With Regards,
Charavana

**Comment by massdosage** [comment]
HiveRunner 3.2.1 was released today which in turn uses:

``<hive.version>1.2.1</hive.version>``

so hopefully this resolves your issue. Let us know if this is not the case.

**Comment by charavana** [comment]
it was hive version 1.2.1 prior your upgrade also  ,my comment was wrong ....kindly upgrade the version from 1.2.1 to 2.X.x

please check if you can read and HQL file with simple unbound proceeding or unbound following in it

**Comment by massdosage** [comment]
Can you please give an example of some HQL that is causing this? Or even better send a unit test that reproduces it. 

Another option would be to try HiveRunner built from this branch:

https://github.com/klarna/HiveRunner/tree/Hive-2.3.0

This is the version we're going to work on next to try get Hive 2.3.x support.
