### ISSUE TITLE
Is it possible to run on a remote HiveRunner and Hadoop installation ?

### ISSUE THREAD

**Issue by ashishsinghi** [klarna/HiveRunner#92]
I would like to have functional testing for my Hive scripts, so it possible to run the test code pointing to an remote Hive server and Hadoop instead of one running on a local JVM.
Thanks.

**Comment by massdosage** [comment]
Please ask questions on the mailing list at https://groups.google.com/forum/#!forum/hive-runner-user rather than raising issues.
