### ISSUE TITLE
Hive Unit test case with TBLProperties

### ISSUE THREAD

**Issue by amitmathapati** [klarna/HiveRunner#95]
I have a query 
CREATE TABLE test_hive_hbase (
key string COMMENT '',
teststr int COMMENT '')
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES (
'hbase.columns.mapping'=':key,teststr:1')
TBLPROPERTIES ('avro.schema.url'='hdfs://${hdfschemapath}')

I need to know using HiveShell how can I specify a avsc file or copy it to tmp dir in the shell?

**Comment by amitmathapati** [comment]
Got this solved.
You can use 'file://${hdfsschemapath} . as it refers the local file

**Comment by massdosage** [comment]
Thanks for describing how you resolved this!
