### ISSUE TITLE
What is the workaround for having a "add jar" in the Hive QL that is being Unit tested

### ISSUE THREAD

**Issue by amitmathapati** [klarna/HiveRunner#96]
I have a Hive QL which has an add jar statement which basically uses UDF function.

How can I unit test that since HiveRunner will not support it? Any tips on the workaround?

**Comment by massdosage** [comment]
If you would like to ask any questions about or discuss HiveRunner please join our mailing list at

https://groups.google.com/forum/#!forum/hive-runner-user
