### ISSUE TITLE
Running Hive Unit Tests in Parallel

### ISSUE THREAD

**Issue by sid88in** [klarna/HiveRunner#97]
I am trying to run multiple tests in parallel and I see 2 options:

1. In each thread, instantiate new HiveShell - but I get an error _Hive Shell already started_
2. Create Hive Shell only once and execute scripts in parallel but two tests with same input tables and different input data might run at the same time. How do we handle that?

Any other option?

thanks
Sid

**Comment by massdosage** [comment]
Could you please repost this as a question on the mailing list (https://groups.google.com/forum/#!forum/hive-runner-user)? We've had a [similar discussion](https://groups.google.com/forum/#!topic/hive-runner-user/papbekJzG4g) in the past so we can refer to that thread and some open branches etc.

**Comment by sid88in** [comment]
thanks. Just applied to be a member :)
